security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        # Registration
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Site
        
        # Admin
        - { path: ^/admin/games/show, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/games$, role: IS_AUTHENTICATED_FULLY }
        
        - { path: ^/admin/profile, role: IS_AUTHENTICATED_FULLY }
        
        - { path: /delete, role: ROLE_SUPER_ADMIN }
        
        - { path: ^/admin/$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: ROLE_ADMIN }